# Terraform docs configuration file
# Only setting non-default values

formatter: "markdown table"
recursive:
  enable: true
  path: terraform


sort:
  by: required
output:
  file: README.md
settings:
  hide-empty: true
  lockfile: false

# content: |-
  # Examples

#   ```hcl
#   {{ include "examples/main.tf" }}
#   ```
