---
- name: Restart Vault
  systemd:
    name: vault
    state: restarted
  when:
    - not packer_build

- name: Reload Vault daemon
  systemd:
    name: vault
    state: restarted
    daemon_reload: true
  when:
    - not packer_build
