- name: Create vault log directory
  ansible.builtin.file:
    path: /var/log/vault
    state: directory
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0700'
  when: vault_audit_enable

- name: Copying rsyslog file
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/31-vault.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload Rsyslog daemon

- name: Copying TLS CA certificate
  ansible.builtin.copy:
    src: '{{ vault_tls_ca_file }}'
    dest: '{{ vault_tls_directory }}/{{ vault_tls_ca_file | basename }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
  when:
    - vault_tls_ca_file is defined
  notify:
    - Restart Vault

- name: Copying TLS certificate and key
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ vault_tls_directory }}/{{ item.dest }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
  with_items:
    - { src: '{{ vault_tls_cert_file }}', dest: '{{ vault_tls_cert_file | basename }}' }
    - { src: '{{ vault_tls_key_file }}', dest: '{{ vault_tls_key_file | basename }}' }
  when:
    - vault_tls_cert_file is defined
    - vault_tls_key_file is defined
  notify:
    - Restart Vault

- name: Copying additional TLS ca, certificate and key
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ vault_tls_directory }}/{{ item.dest }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
  with_items:
    - { src: '{{ vault_additional_tls_ca_file }}', dest: '{{ vault_additional_tls_ca_file | basename }}' }
    - { src: '{{ vault_additional_tls_cert_file }}', dest: '{{ vault_additional_tls_cert_file | basename }}' }
    - { src: '{{ vault_additional_tls_key_file }}', dest: '{{ vault_additional_tls_key_file | basename }}' }
  when:
    - vault_additional_tls_ca_file is defined
    - vault_additional_tls_cert_file is defined
    - vault_additional_tls_key_file is defined
  notify:
    - Restart Vault

- name: Copying Vault license file
  ansible.builtin.copy:
    src: '{{ vault_license_file }}'
    dest: '{{ vault_license_directory }}/vault.hclic'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
  when:
    - vault_license_file is defined

- name: Creating Vault license file
  ansible.builtin.copy:
    dest: '{{ vault_license_directory }}/vault.hclic'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
    content: '{{ vault_license_string }}'
  when:
    - vault_license_string is defined

- name: Templating out Vault configuration
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: '{{ vault_config_file }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0660'
  notify:
    - Restart Vault

- name: Creating service environment file
  ansible.builtin.file:
    path: '{{ vault_home_directory }}/vault.env'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0640'
    state: touch
    access_time: preserve
    modification_time: preserve
  notify:
    - Reload Vault daemon

- name: Templating out systemd script
  ansible.builtin.template:
    src: vault.systemd.j2
    dest: /lib/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload Vault daemon

- name: Starting and enabling Vault
  ansible.builtin.systemd:
    name: vault
    enabled: true
    state: started
