# https://taskfile.dev
version: '3'

vars:
  VSO_CHART_VERSION: 0.9.1

tasks:
  all:
    cmds:
      - task: tf-apply
      - task: gke-credentials

  tf-plan:
    aliases: ["plan", "tfp"]
    cmds:
      - terraform init
      - terraform plan

  tf-apply:
    cmds:
      - terraform init
      - terraform apply -auto-approve

  tf-destroy:
    aliases: ["gke-destroy"]
    cmds:
      - terraform init
      - terraform destroy -auto-approve

  gke-credentials:
    desc: Get GKE credentials
    cmds:
      - gcloud container clusters get-credentials {{ .CLUSTER }} --region {{ .REGION }} --dns-endpoint
      - kubectl cluster-info
    vars:
      CLUSTER:
        sh: terraform output -raw gke_cluster_name
      REGION:
        sh: terraform output -raw region

  bastion-ssh:
    desc: SSH into bastion
    cmds:
      - gcloud compute ssh {{ .INSTANCE }} --zone {{ .ZONE }} --tunnel-through-iap
    vars:
      INSTANCE:
        sh: terraform output -raw bastion_name
      ZONE:
        sh: terraform output -raw bastion_zone

  gke-down:
    desc: Scale down GKE cluster
    cmds:
      - gcloud container clusters resize {{ .CLUSTER }} --region {{ .REGION }} --num-nodes {{ .SIZE }} --quiet  --async
    vars:
      CLUSTER:
        sh: terraform output -raw gke_cluster_name
      REGION:
        sh: terraform output -raw region
      SIZE: 0

  gke-up:
    desc: Scale up GKE cluster
    cmds:
      - gcloud container clusters resize {{ .CLUSTER }} --region {{ .REGION }} --num-nodes {{ .SIZE }} --quiet --async
    vars:
      CLUSTER:
        sh: terraform output -raw gke_cluster_name
      REGION:
        sh: terraform output -raw region
      SIZE: 1

  redeploy:
    cmds:
      - terraform destroy -auto-approve -target="google_container_cluster.default"
      - sleep 30
      - terraform apply -auto-approve
